# Generated by Django 5.2.4 on 2025-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoneticiekrani", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
